name:                rockets-stream
version:             0.1.0.0
github:              "sarangj/rockets-stream"
license:             BSD3
author:              "Sarang Joshi"
maintainer:          "sarangjoshi22@gmail.com"
copyright:           "2018 Sarang Joshi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sarangj/rockets-stream#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- configurator
- data-default
- http-conduit
- http-types
- reddit
- text
- time
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  rockets-stream-dry-run:
    main:                DryRun.hs
    source-dirs:         app
    ghc-options:
    - -main-is DryRun
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rockets-stream
  
  rockets-stream:
    main:                XPost.hs
    source-dirs:         app
    ghc-options:
    - -main-is XPost
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rockets-stream

tests:
  rockets-stream-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rockets-stream
